package com.kannada.kanuaconv.maps;

import java.lang.reflect.Array;
import java.util.ArrayList;
import java.util.Comparator;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class ConversionMap implements CharacterMap {
	
	static Map<String, String> kuvToUniCMap = new HashMap<String, String>();

	public static ASCIIUNIMAP[]  asciiUniMap = new ASCIIUNIMAP[717];
	public static List<String> ottaksharaList = new ArrayList<String>();
	public static List<String> gunitakshara = new ArrayList<String>();
	//String outString = new String();

	public static class ASCIIUNIMAP {
		public String textASCII;
		public String textUNI;
		public int asciiLength;
		public int uniLength; 
		
		
		public ASCIIUNIMAP(String textASCII, String textUNI) {
			this.textASCII = textASCII;
			this.textUNI = textUNI;
			this.asciiLength = textASCII.length();
			this.uniLength = textUNI.length();
		}

		@Override
		public String toString() {
			return "ASCIIUNIMAP [textUNI=" + textUNI + "]";
		}

		/* (non-Javadoc)
		 * @see java.lang.Object#equals(java.lang.Object)
		 */
		@Override
		public boolean equals(Object arg0) {
			// TODO Auto-generated method stub
			return super.equals(arg0);
		}
		
	}
	
	public static boolean initializeMaps(){
            
asciiUniMap[0] =  new ASCIIUNIMAP("¥sóÉÆÃ","ಫೋ಼");
asciiUniMap[1] =  new ASCIIUNIMAP("zsÉÆÃ","ಧೋ");
asciiUniMap[2] =  new ASCIIUNIMAP("qsÉÆÃ","ಢೋ");
asciiUniMap[3] =  new ASCIIUNIMAP("PÀë÷Ú","ಕ್ಷ್ಣ");
asciiUniMap[4] =  new ASCIIUNIMAP("gÀhiï","ಝ್");
asciiUniMap[5] =  new ASCIIUNIMAP("AiÉÆÃ","ಯೋ");
asciiUniMap[6] =  new ASCIIUNIMAP("AiÉÄÊ","ಯೈ");
asciiUniMap[7] =  new ASCIIUNIMAP("AiÉÄÃ","ಯೇ");
asciiUniMap[8] =  new ASCIIUNIMAP("AiÀiï","ಯ್");
asciiUniMap[9] =  new ASCIIUNIMAP("AiÀiË","ಯೌ");
asciiUniMap[10] =  new ASCIIUNIMAP("AiÀiÁ","ಯಾ");
asciiUniMap[11] =  new ASCIIUNIMAP("AiÀÄÈ","ಯೃ");
asciiUniMap[12] =  new ASCIIUNIMAP("AiÀÄB","ಯಃ");
asciiUniMap[13] =  new ASCIIUNIMAP("AiÀÄÆ","ಯೂ");
asciiUniMap[14] =  new ASCIIUNIMAP("AiÀÄÄ","ಯು");
asciiUniMap[15] =  new ASCIIUNIMAP("¥sÉÇÃ","ಫೋ");
asciiUniMap[16] =  new ASCIIUNIMAP("¨sÉÆÃ","ಭೋ");
asciiUniMap[17] =  new ASCIIUNIMAP("gÀhiÁ","ಝಾ");
asciiUniMap[18] =  new ASCIIUNIMAP("gÀhÄÄ","ಝು");
asciiUniMap[19] =  new ASCIIUNIMAP("gÀhÄÆ","ಝೂ");
asciiUniMap[20] =  new ASCIIUNIMAP("gÀhÄÈ","ಝೃ");
asciiUniMap[21] =  new ASCIIUNIMAP("gÉhÄÃ","ಝೇ");
asciiUniMap[22] =  new ASCIIUNIMAP("gÉhÄÊ","ಝೈ");
asciiUniMap[23] =  new ASCIIUNIMAP("gÉhÆÃ","ಝೋ");
asciiUniMap[24] =  new ASCIIUNIMAP("gÀhiË","ಝೌ");
asciiUniMap[25] =  new ASCIIUNIMAP("¥sÉÆÃ","ಫೋ");
asciiUniMap[26] =  new ASCIIUNIMAP("PÉëöÊ","ಕ್ಷೈ");
asciiUniMap[27] =  new ASCIIUNIMAP("PÉëÆÃ","ಕ್ಷೋ");
asciiUniMap[28] =  new ASCIIUNIMAP("eÉÕöÊ","ಜ್ಞೈ");
asciiUniMap[29] =  new ASCIIUNIMAP("eÉÆÕÃ","ಜ್ಞೋ");
asciiUniMap[30] =  new ASCIIUNIMAP("SÉÆÃó","ಖೋ಼");
asciiUniMap[31] =  new ASCIIUNIMAP("eóÉÆÃ","ಜೋ಼");
asciiUniMap[32] =  new ASCIIUNIMAP("¥sóÀÄ","ಫು಼");
asciiUniMap[33] =  new ASCIIUNIMAP("¥sóÀÆ","ಫೂ಼");
asciiUniMap[34] =  new ASCIIUNIMAP("¥sóÀÈ","ಫೃ಼");
asciiUniMap[35] =  new ASCIIUNIMAP("¥sóÉÃ","ಫೇ಼");
asciiUniMap[36] =  new ASCIIUNIMAP("¥sóÉÊ","ಫೈ಼");
asciiUniMap[37] =  new ASCIIUNIMAP("¥sóÉÆ","ಫೊ಼");
asciiUniMap[38] =  new ASCIIUNIMAP("gÀhÄñ","ಝೄ");
asciiUniMap[39] =  new ASCIIUNIMAP("AiÀÄñ","ಯೄ");
asciiUniMap[40] =  new ASCIIUNIMAP("PÉëöÊ","ಕ್ಷೈ");
asciiUniMap[41] =  new ASCIIUNIMAP("eÉÕöÊ","ಜ್ಞೈ");
asciiUniMap[42] =  new ASCIIUNIMAP("gÀhÄ","ಝ");
asciiUniMap[43] =  new ASCIIUNIMAP("zsÉÊ","ಧೈ");
asciiUniMap[44] =  new ASCIIUNIMAP("zsÉÆ","ಧೊ");
asciiUniMap[45] =  new ASCIIUNIMAP("zsÉÃ","ಧೇ");
asciiUniMap[46] =  new ASCIIUNIMAP("zsÀÈ","ಧೃ");
asciiUniMap[47] =  new ASCIIUNIMAP("zsÀB","ಧಃ");
asciiUniMap[48] =  new ASCIIUNIMAP("zsÀÆ","ಧೂ");
asciiUniMap[49] =  new ASCIIUNIMAP("zsÀÄ","ಧು");
asciiUniMap[50] =  new ASCIIUNIMAP("ZÉÆÃ","ಚೋ");
asciiUniMap[51] =  new ASCIIUNIMAP("YÉÆÃ","ಙೋ");
asciiUniMap[52] =  new ASCIIUNIMAP("xÉÆÃ","ಥೋ");
asciiUniMap[53] =  new ASCIIUNIMAP("WÉÆÃ","ಘೋ");
asciiUniMap[54] =  new ASCIIUNIMAP("vÉÆÃ","ತೋ");
asciiUniMap[55] =  new ASCIIUNIMAP("UÉÆÃ","ಗೋ");
asciiUniMap[56] =  new ASCIIUNIMAP("SÉÆÃ","ಖೋ");
asciiUniMap[57] =  new ASCIIUNIMAP("qsÉÊ","ಢೈ");
asciiUniMap[58] =  new ASCIIUNIMAP("qsÉÆ","ಢೊ");
asciiUniMap[59] =  new ASCIIUNIMAP("qsÉÃ","ಢೇ");
asciiUniMap[60] =  new ASCIIUNIMAP("qsÀÈ","ಢೃ");
asciiUniMap[61] =  new ASCIIUNIMAP("qsÀB","ಢಃ");
asciiUniMap[62] =  new ASCIIUNIMAP("qsÀÆ","ಢೂ");
asciiUniMap[63] =  new ASCIIUNIMAP("qsÀÄ","ಢು");
asciiUniMap[64] =  new ASCIIUNIMAP("qÉÆÃ","ಡೋ");
asciiUniMap[65] =  new ASCIIUNIMAP("Që÷Ú","ಕ್ಷ್ಣಿ");
asciiUniMap[66] =  new ASCIIUNIMAP("PÉÆÃ","ಕೋ");
asciiUniMap[67] =  new ASCIIUNIMAP("ºÉÇÃ","ಹೋ");
asciiUniMap[68] =  new ASCIIUNIMAP("oÉÆÃ","ಠೋ");
asciiUniMap[69] =  new ASCIIUNIMAP("mÉÆÃ","ಟೋ");
asciiUniMap[70] =  new ASCIIUNIMAP("kÉÆÃ","ಞೋ");
asciiUniMap[71] =  new ASCIIUNIMAP("gÉÆÃ","ರೋ");
asciiUniMap[72] =  new ASCIIUNIMAP("eÉÆÃ","ಜೋ");
asciiUniMap[73] =  new ASCIIUNIMAP("bÉÆÃ","ಛೋ");
asciiUniMap[74] =  new ASCIIUNIMAP("AiÉÆ","ಯೊ");
asciiUniMap[75] =  new ASCIIUNIMAP("AiÉÄ","ಯೆ");
asciiUniMap[76] =  new ASCIIUNIMAP("AiÀÄ","ಯ");
asciiUniMap[77] =  new ASCIIUNIMAP("ªÉÇÃ","ವೋ");
asciiUniMap[78] =  new ASCIIUNIMAP("ªÉÆÃ","ಮೋ");
asciiUniMap[79] =  new ASCIIUNIMAP("ªÉÄÊ","ಮೈ");
asciiUniMap[80] =  new ASCIIUNIMAP("ªÉÄÃ","ಮೇ");
asciiUniMap[81] =  new ASCIIUNIMAP("ªÀiï","ಮ್");
asciiUniMap[82] =  new ASCIIUNIMAP("ªÀiË","ಮೌ");
asciiUniMap[83] =  new ASCIIUNIMAP("ªÀiÁ","ಮಾ");
asciiUniMap[84] =  new ASCIIUNIMAP("ªÀÄÈ","ಮೃ");
asciiUniMap[85] =  new ASCIIUNIMAP("ªÀÄB","ಮಃ");
asciiUniMap[86] =  new ASCIIUNIMAP("ªÀÄÆ","ಮೂ");
asciiUniMap[87] =  new ASCIIUNIMAP("ªÀÄÄ","ಮು");
asciiUniMap[88] =  new ASCIIUNIMAP("¼ÉÆÃ","ಳೋ");
asciiUniMap[89] =  new ASCIIUNIMAP("µÉÆÃ","ಷೋ");
asciiUniMap[90] =  new ASCIIUNIMAP("¥sÉÊ","ಫೈ");
asciiUniMap[91] =  new ASCIIUNIMAP("¥sÉÇ","ಫೊ");
asciiUniMap[92] =  new ASCIIUNIMAP("¥sÉÃ","ಫೇ");
asciiUniMap[93] =  new ASCIIUNIMAP("¥sÀÈ","ಫೃ");
asciiUniMap[94] =  new ASCIIUNIMAP("¥sÀÇ","ಫೂ");
asciiUniMap[95] =  new ASCIIUNIMAP("¥sÀB","ಫಃ");
asciiUniMap[96] =  new ASCIIUNIMAP("¥sÀÅ","ಫು");
asciiUniMap[97] =  new ASCIIUNIMAP("¥ÉÇÃ","ಪೋ");
asciiUniMap[98] =  new ASCIIUNIMAP("£ÉÆÃ","ನೋ");
asciiUniMap[99] =  new ASCIIUNIMAP("±ÉÆÃ","ಶೋ");
asciiUniMap[100] =  new ASCIIUNIMAP("¸ÉÆÃ","ಸೋ");
asciiUniMap[101] =  new ASCIIUNIMAP("¯ÉÆÃ","ಲೋ");
asciiUniMap[102] =  new ASCIIUNIMAP("¨sÉÊ","ಭೈ");
asciiUniMap[103] =  new ASCIIUNIMAP("¨sÉÆ","ಭೊ");
asciiUniMap[104] =  new ASCIIUNIMAP("¨sÉÃ","ಭೇ");
asciiUniMap[105] =  new ASCIIUNIMAP("¨sÀÈ","ಭೃ");
asciiUniMap[106] =  new ASCIIUNIMAP("¨sÀB","ಭಃ");
asciiUniMap[107] =  new ASCIIUNIMAP("¨sÀÆ","ಭೂ");
asciiUniMap[108] =  new ASCIIUNIMAP("¨sÀÄ","ಭು");
asciiUniMap[109] =  new ASCIIUNIMAP("¨ÉÆÃ","ಬೋ");
asciiUniMap[110] =  new ASCIIUNIMAP("ºÉÆÃ","ಹೋ");
asciiUniMap[111] =  new ASCIIUNIMAP("zÉÆÃ","ದೋ");
asciiUniMap[112] =  new ASCIIUNIMAP("±ÀÉÃ","ಶೇ");
asciiUniMap[113] =  new ASCIIUNIMAP("ºÀÄ","ಹು");
asciiUniMap[114] =  new ASCIIUNIMAP("ºÀÅ","ಹು");
asciiUniMap[115] =  new ASCIIUNIMAP("ºÀÆ","ಹೂ");
asciiUniMap[116] =  new ASCIIUNIMAP("ºÀÇ","ಹೂ");
asciiUniMap[117] =  new ASCIIUNIMAP("«iÁ","ಮೀ");
asciiUniMap[118] =  new ASCIIUNIMAP("jhÄÃ","ಝೀ");
asciiUniMap[119] =  new ASCIIUNIMAP("gÉhÄ","ಝೆ");
asciiUniMap[120] =  new ASCIIUNIMAP("gÉhÆ","ಝೊ");
asciiUniMap[121] =  new ASCIIUNIMAP("¥ÉÆÃ","ಪೋ");
asciiUniMap[122] =  new ASCIIUNIMAP("¥sÀÄ","ಫು");
asciiUniMap[123] =  new ASCIIUNIMAP("¥sÀÆ","ಫೂ");
asciiUniMap[124] =  new ASCIIUNIMAP("¥sÉÆ","ಫೊ");
asciiUniMap[125] =  new ASCIIUNIMAP("PÀëÄ","ಕ್ಷು");
asciiUniMap[126] =  new ASCIIUNIMAP("PÀëÆ","ಕ್ಷೂ");
asciiUniMap[127] =  new ASCIIUNIMAP("PÀëø","ಕ್ಷೃ");
asciiUniMap[128] =  new ASCIIUNIMAP("PÉëÃ","ಕ್ಷೇ");
asciiUniMap[129] =  new ASCIIUNIMAP("PÉëÆ","ಕ್ಷೊ");
asciiUniMap[130] =  new ASCIIUNIMAP("eÉÕÃ","ಜ್ಞೇ");
asciiUniMap[131] =  new ASCIIUNIMAP("eÉÆÕ","ಜ್ಞೊ");
asciiUniMap[132] =  new ASCIIUNIMAP("TÃóó","ಖೀ಼");
asciiUniMap[133] =  new ASCIIUNIMAP("SÉÃó","ಖೇ಼");
asciiUniMap[134] =  new ASCIIUNIMAP("SÉÊó","ಖೈ಼");
asciiUniMap[135] =  new ASCIIUNIMAP("SÉÆó","ಖೊ಼");
asciiUniMap[136] =  new ASCIIUNIMAP("eóÉÃ","ಜೇ಼");
asciiUniMap[137] =  new ASCIIUNIMAP("eóÉÊ","ಜೈ಼");
asciiUniMap[138] =  new ASCIIUNIMAP("eóÉÆ","ಜೊ಼");
asciiUniMap[139] =  new ASCIIUNIMAP("¥sóÀ","ಫ಼");
asciiUniMap[140] =  new ASCIIUNIMAP("¥sóÁ","ಫಾ಼");
asciiUniMap[141] =  new ASCIIUNIMAP("¦üûÃ","ಫೀ಼");
asciiUniMap[142] =  new ASCIIUNIMAP("¥sóÉ","ಫೆ಼");
asciiUniMap[143] =  new ASCIIUNIMAP("¥sóË","ಫೌ಼");
asciiUniMap[144] =  new ASCIIUNIMAP("qsÀñ","ಢೄ");
asciiUniMap[145] =  new ASCIIUNIMAP("zsÀñ","ಧೄ");
asciiUniMap[146] =  new ASCIIUNIMAP("¥sÀñ","ಫೄ");
asciiUniMap[147] =  new ASCIIUNIMAP("¨sÀñ","ಭೄ");
asciiUniMap[148] =  new ASCIIUNIMAP("ªÀÄñ","ಮೄ");
asciiUniMap[149] =  new ASCIIUNIMAP("uÉÆÃ","ಣೋ");
asciiUniMap[150] =  new ASCIIUNIMAP("zÉÆÃ","ದೋ");
asciiUniMap[151] =  new ASCIIUNIMAP("ºÉÆ","ಹೊ");
asciiUniMap[152] =  new ASCIIUNIMAP("«iÁ","ಮೀ");
asciiUniMap[153] =  new ASCIIUNIMAP("zsï","ಧ್");
asciiUniMap[154] =  new ASCIIUNIMAP("zsË","ಧೌ");
asciiUniMap[155] =  new ASCIIUNIMAP("zsÉ","ಧೆ");
asciiUniMap[156] =  new ASCIIUNIMAP("zsÀ","ಧ");
asciiUniMap[157] =  new ASCIIUNIMAP("zsÁ","ಧಾ");
asciiUniMap[158] =  new ASCIIUNIMAP("ZÉÊ","ಚೈ");
asciiUniMap[159] =  new ASCIIUNIMAP("ZÉÆ","ಚೊ");
asciiUniMap[160] =  new ASCIIUNIMAP("ZÉÃ","ಚೇ");
asciiUniMap[161] =  new ASCIIUNIMAP("ZÀÈ","ಚೃ");
asciiUniMap[162] =  new ASCIIUNIMAP("ZÀB","ಚಃ");
asciiUniMap[163] =  new ASCIIUNIMAP("ZÀÆ","ಚೂ");
asciiUniMap[164] =  new ASCIIUNIMAP("ZÀÄ","ಚು");
asciiUniMap[165] =  new ASCIIUNIMAP("YÉÊ","ಙೈ");
asciiUniMap[166] =  new ASCIIUNIMAP("YÉÆ","ಙೊ");
asciiUniMap[167] =  new ASCIIUNIMAP("YÉÃ","ಙೇ");
asciiUniMap[168] =  new ASCIIUNIMAP("YÂÃ","ಙೀ");
asciiUniMap[169] =  new ASCIIUNIMAP("xÉÊ","ಥೈ");
asciiUniMap[170] =  new ASCIIUNIMAP("xÉÆ","ಥೊ");
asciiUniMap[171] =  new ASCIIUNIMAP("xÉÃ","ಥೇ");
asciiUniMap[172] =  new ASCIIUNIMAP("xÀÈ","ಥೃ");
asciiUniMap[173] =  new ASCIIUNIMAP("xÀB","ಥಃ");
asciiUniMap[174] =  new ASCIIUNIMAP("xÀÆ","ಥೂ");
asciiUniMap[175] =  new ASCIIUNIMAP("xÀÄ","ಥು");
asciiUniMap[176] =  new ASCIIUNIMAP("WÉÆ","ಘೊ");
asciiUniMap[177] =  new ASCIIUNIMAP("WÉÃ","ಘೇ");
asciiUniMap[178] =  new ASCIIUNIMAP("WÀÈ","ಘೃ");
asciiUniMap[179] =  new ASCIIUNIMAP("WÀB","ಘಃ");
asciiUniMap[180] =  new ASCIIUNIMAP("WÀÆ","ಘೂ");
asciiUniMap[181] =  new ASCIIUNIMAP("WÀÄ","ಘು");
asciiUniMap[182] =  new ASCIIUNIMAP("±ÀÉ","ಶೆ");
asciiUniMap[183] =  new ASCIIUNIMAP("vÉÊ","ತೈ");
asciiUniMap[184] =  new ASCIIUNIMAP("vÉÆ","ತೊ");
asciiUniMap[185] =  new ASCIIUNIMAP("vÉÃ","ತೇ");
asciiUniMap[186] =  new ASCIIUNIMAP("vÀÈ","ತೃ");
asciiUniMap[187] =  new ASCIIUNIMAP("vÀB","ತಃ");
asciiUniMap[188] =  new ASCIIUNIMAP("vÀÆ","ತೂ");
asciiUniMap[189] =  new ASCIIUNIMAP("vÀÄ","ತು");
asciiUniMap[190] =  new ASCIIUNIMAP("UÉÊ","ಗೈ");
asciiUniMap[191] =  new ASCIIUNIMAP("UÉÆ","ಗೊ");
asciiUniMap[192] =  new ASCIIUNIMAP("UÉÃ","ಗೇ");
asciiUniMap[193] =  new ASCIIUNIMAP("UÀÈ","ಗೃ");
asciiUniMap[194] =  new ASCIIUNIMAP("UÀB","ಗಃ");
asciiUniMap[195] =  new ASCIIUNIMAP("UÀÆ","ಗೂ");
asciiUniMap[196] =  new ASCIIUNIMAP("UÀÄ","ಗು");
asciiUniMap[197] =  new ASCIIUNIMAP("tÂÃ","ಣೀ");
asciiUniMap[198] =  new ASCIIUNIMAP("SÉÊ","ಖೈ");
asciiUniMap[199] =  new ASCIIUNIMAP("SÉÆ","ಖೊ");
asciiUniMap[200] =  new ASCIIUNIMAP("SÉÃ","ಖೇ");
asciiUniMap[201] =  new ASCIIUNIMAP("rüÃ","ಢೀ");
asciiUniMap[202] =  new ASCIIUNIMAP("qsï","ಢ್");
asciiUniMap[203] =  new ASCIIUNIMAP("qsË","ಢೌ");
asciiUniMap[204] =  new ASCIIUNIMAP("qsÉ","ಢೆ");
asciiUniMap[205] =  new ASCIIUNIMAP("qsÀ","ಢ");
asciiUniMap[206] =  new ASCIIUNIMAP("qsÁ","ಢಾ");
asciiUniMap[207] =  new ASCIIUNIMAP("qÉÊ","ಡೈ");
asciiUniMap[208] =  new ASCIIUNIMAP("qÉÆ","ಡೊ");
asciiUniMap[209] =  new ASCIIUNIMAP("qÉÃ","ಡೇ");
asciiUniMap[210] =  new ASCIIUNIMAP("qÀÈ","ಡೃ");
asciiUniMap[211] =  new ASCIIUNIMAP("qÀB","ಡಃ");
asciiUniMap[212] =  new ASCIIUNIMAP("qÀÆ","ಡೂ");
asciiUniMap[213] =  new ASCIIUNIMAP("qÀÄ","ಡು");
asciiUniMap[214] =  new ASCIIUNIMAP("Pïë","ಕ್ಷ್");
asciiUniMap[215] =  new ASCIIUNIMAP("PÉÊ","ಕೈ");
asciiUniMap[216] =  new ASCIIUNIMAP("PÉÆ","ಕೊ");
asciiUniMap[217] =  new ASCIIUNIMAP("PÉÃ","ಕೇ");
asciiUniMap[218] =  new ASCIIUNIMAP("PÀë","ಕ್ಷ");
asciiUniMap[219] =  new ASCIIUNIMAP("PÀÈ","ಕೃ");
asciiUniMap[220] =  new ASCIIUNIMAP("PÀB","ಕಃ");
asciiUniMap[221] =  new ASCIIUNIMAP("PÀÆ","ಕೂ");
asciiUniMap[222] =  new ASCIIUNIMAP("PÀÄ","ಕು");
asciiUniMap[223] =  new ASCIIUNIMAP("ºÉÊ","ಹೈ");
asciiUniMap[224] =  new ASCIIUNIMAP("oÉÊ","ಠೈ");
asciiUniMap[225] =  new ASCIIUNIMAP("ºÉÇ","ಹೊ");
asciiUniMap[226] =  new ASCIIUNIMAP("oÉÆ","ಠೊ");
asciiUniMap[227] =  new ASCIIUNIMAP("ºÉÃ","ಹೇ");
asciiUniMap[228] =  new ASCIIUNIMAP("oÉÃ","ಠೇ");
asciiUniMap[229] =  new ASCIIUNIMAP("ºÀÈ","ಹೃ");
asciiUniMap[230] =  new ASCIIUNIMAP("oÀÈ","ಠೃ");
asciiUniMap[231] =  new ASCIIUNIMAP("ºÀÇ","ಹೂ");
asciiUniMap[232] =  new ASCIIUNIMAP("ºÀB","ಹಃ");
asciiUniMap[233] =  new ASCIIUNIMAP("oÀB","ಠಃ");
asciiUniMap[234] =  new ASCIIUNIMAP("oÀÆ","ಠೂ");
asciiUniMap[235] =  new ASCIIUNIMAP("ºÀÅ","ಹು");
asciiUniMap[236] =  new ASCIIUNIMAP("oÀÄ","ಠು");
asciiUniMap[237] =  new ASCIIUNIMAP("mÉÊ","ಟೈ");
asciiUniMap[238] =  new ASCIIUNIMAP("mÉÆ","ಟೊ");
asciiUniMap[239] =  new ASCIIUNIMAP("mÉÃ","ಟೇ");
asciiUniMap[240] =  new ASCIIUNIMAP("kÉÊ","ಞೈ");
asciiUniMap[241] =  new ASCIIUNIMAP("kÉÆ","ಞೊ");
asciiUniMap[242] =  new ASCIIUNIMAP("kÉÃ","ಞೇ");
asciiUniMap[243] =  new ASCIIUNIMAP("kÂÃ","ಞೀ");
asciiUniMap[244] =  new ASCIIUNIMAP("jhÄ","ಝಿ");
asciiUniMap[245] =  new ASCIIUNIMAP("gÉÊ","ರೈ");
asciiUniMap[246] =  new ASCIIUNIMAP("gÉÆ","ರೊ");
asciiUniMap[247] =  new ASCIIUNIMAP("gÉÃ","ರೇ");
asciiUniMap[248] =  new ASCIIUNIMAP("gÀÈ","ರೃ");
asciiUniMap[249] =  new ASCIIUNIMAP("gÀB","ರಃ");
asciiUniMap[250] =  new ASCIIUNIMAP("gÀÆ","ರೂ");
asciiUniMap[251] =  new ASCIIUNIMAP("gÀÄ","ರು");
asciiUniMap[252] =  new ASCIIUNIMAP("eïÕ","ಜ್ಞ್");
asciiUniMap[253] =  new ASCIIUNIMAP("eÉÊ","ಜೈ");
asciiUniMap[254] =  new ASCIIUNIMAP("eÉÆ","ಜೊ");
asciiUniMap[255] =  new ASCIIUNIMAP("eÉÃ","ಜೇ");
asciiUniMap[256] =  new ASCIIUNIMAP("bÉÊ","ಛೈ");
asciiUniMap[257] =  new ASCIIUNIMAP("bÉÆ","ಛೊ");
asciiUniMap[258] =  new ASCIIUNIMAP("bÉÃ","ಛೇ");
asciiUniMap[259] =  new ASCIIUNIMAP("bÀÈ","ಛೃ");
asciiUniMap[260] =  new ASCIIUNIMAP("bÀB","ಛಃ");
asciiUniMap[261] =  new ASCIIUNIMAP("bÀÆ","ಛೂ");
asciiUniMap[262] =  new ASCIIUNIMAP("bÀÄ","ಛು");
asciiUniMap[263] =  new ASCIIUNIMAP("ªÉÊ","ವೈ");
asciiUniMap[264] =  new ASCIIUNIMAP("ªÉÇ","ವೊ");
asciiUniMap[265] =  new ASCIIUNIMAP("ªÉÆ","ಮೊ");
asciiUniMap[266] =  new ASCIIUNIMAP("ªÉÃ","ವೇ");
asciiUniMap[267] =  new ASCIIUNIMAP("ªÉÄ","ಮೆ");
asciiUniMap[268] =  new ASCIIUNIMAP("ªÀÈ","ವೃ");
asciiUniMap[269] =  new ASCIIUNIMAP("ªÀÇ","ವೂ");
asciiUniMap[270] =  new ASCIIUNIMAP("ªÀB","ವಃ");
asciiUniMap[271] =  new ASCIIUNIMAP("ªÀÅ","ವು");
asciiUniMap[272] =  new ASCIIUNIMAP("ªÀÄ","ಮ");
asciiUniMap[273] =  new ASCIIUNIMAP("¼ÉÊ","ಳೈ");
asciiUniMap[274] =  new ASCIIUNIMAP("¼ÉÆ","ಳೊ");
asciiUniMap[275] =  new ASCIIUNIMAP("¼ÉÃ","ಳೇ");
asciiUniMap[276] =  new ASCIIUNIMAP("¼ÀÈ","ಳೃ");
asciiUniMap[277] =  new ASCIIUNIMAP("¼ÀB","ಳಃ");
asciiUniMap[278] =  new ASCIIUNIMAP("¼ÀÆ","ಳೂ");
asciiUniMap[279] =  new ASCIIUNIMAP("¼ÀÄ","ಳು");
asciiUniMap[280] =  new ASCIIUNIMAP("µÉÊ","ಷೈ");
asciiUniMap[281] =  new ASCIIUNIMAP("µÉÆ","ಷೊ");
asciiUniMap[282] =  new ASCIIUNIMAP("µÉÃ","ಷೇ");
asciiUniMap[283] =  new ASCIIUNIMAP("µÀï","ಷ್");
asciiUniMap[284] =  new ASCIIUNIMAP("µÀÈ","ಷೃ");
asciiUniMap[285] =  new ASCIIUNIMAP("µÀB","ಷಃ");
asciiUniMap[286] =  new ASCIIUNIMAP("µÀÆ","ಷೂ");
asciiUniMap[287] =  new ASCIIUNIMAP("µÀÄ","ಷು");
asciiUniMap[288] =  new ASCIIUNIMAP("¬ÄÃ","ಯೀ");
asciiUniMap[289] =  new ASCIIUNIMAP("©üÃ","ಭೀ");
asciiUniMap[290] =  new ASCIIUNIMAP("¥sï","ಫ್");
asciiUniMap[291] =  new ASCIIUNIMAP("¥sË","ಫೌ");
asciiUniMap[292] =  new ASCIIUNIMAP("¥sÉ","ಫೆ");
asciiUniMap[293] =  new ASCIIUNIMAP("¥sÀ","ಫ");
asciiUniMap[294] =  new ASCIIUNIMAP("¥sÁ","ಫಾ");
asciiUniMap[295] =  new ASCIIUNIMAP("¥ÉÊ","ಪೈ");
asciiUniMap[296] =  new ASCIIUNIMAP("¥ÉÇ","ಪೊ");
asciiUniMap[297] =  new ASCIIUNIMAP("¥ÉÃ","ಪೇ");
asciiUniMap[298] =  new ASCIIUNIMAP("¥ÀÈ","ಪೃ");
asciiUniMap[299] =  new ASCIIUNIMAP("¥ÀÇ","ಪೂ");
asciiUniMap[300] =  new ASCIIUNIMAP("¥ÀB","ಪಃ");
asciiUniMap[301] =  new ASCIIUNIMAP("¥ÀÅ","ಪು");
asciiUniMap[302] =  new ASCIIUNIMAP("£ÉÊ","ನೈ");
asciiUniMap[303] =  new ASCIIUNIMAP("£ÉÆ","ನೊ");
asciiUniMap[304] =  new ASCIIUNIMAP("£ÉÃ","ನೇ");
asciiUniMap[305] =  new ASCIIUNIMAP("£ÀÈ","ನೃ");
asciiUniMap[306] =  new ASCIIUNIMAP("£ÀB","ನಃ");
asciiUniMap[307] =  new ASCIIUNIMAP("£ÀÆ","ನೂ");
asciiUniMap[308] =  new ASCIIUNIMAP("£ÀÄ","ನು");
asciiUniMap[309] =  new ASCIIUNIMAP("¢üÃ","ಧೀ");
asciiUniMap[310] =  new ASCIIUNIMAP("«ÄÃ","ಮೀ");
asciiUniMap[311] =  new ASCIIUNIMAP("±ÉÊ","ಶೈ");
asciiUniMap[312] =  new ASCIIUNIMAP("±ÉÆ","ಶೊ");
asciiUniMap[313] =  new ASCIIUNIMAP("±ÉÃ","ಶೇ");
asciiUniMap[314] =  new ASCIIUNIMAP("±ÀÈ","ಶೃ");
asciiUniMap[315] =  new ASCIIUNIMAP("±ÀB","ಶಃ");
asciiUniMap[316] =  new ASCIIUNIMAP("±ÀÆ","ಶೂ");
asciiUniMap[317] =  new ASCIIUNIMAP("±ÀÄ","ಶು");
asciiUniMap[318] =  new ASCIIUNIMAP("ºÀÄ","ಹು");
asciiUniMap[319] =  new ASCIIUNIMAP("ºÀÆ","ಹೂ");
asciiUniMap[320] =  new ASCIIUNIMAP("¸ÉÊ","ಸೈ");
asciiUniMap[321] =  new ASCIIUNIMAP("¸ÉÆ","ಸೊ");
asciiUniMap[322] =  new ASCIIUNIMAP("¸ÉÃ","ಸೇ");
asciiUniMap[323] =  new ASCIIUNIMAP("¸ÀÈ","ಸೃ");
asciiUniMap[324] =  new ASCIIUNIMAP("¸ÀB","ಸಃ");
asciiUniMap[325] =  new ASCIIUNIMAP("¸ÀÆ","ಸೂ");
asciiUniMap[326] =  new ASCIIUNIMAP("¸ÀÄ","ಸು");
asciiUniMap[327] =  new ASCIIUNIMAP("¯ÉÊ","ಲೈ");
asciiUniMap[328] =  new ASCIIUNIMAP("¯ÉÆ","ಲೊ");
asciiUniMap[329] =  new ASCIIUNIMAP("¯ÉÃ","ಲೇ");
asciiUniMap[330] =  new ASCIIUNIMAP("¨sï","ಭ್");
asciiUniMap[331] =  new ASCIIUNIMAP("¨sË","ಭೌ");
asciiUniMap[332] =  new ASCIIUNIMAP("¨sÉ","ಭೆ");
asciiUniMap[333] =  new ASCIIUNIMAP("¨sÀ","ಭ");
asciiUniMap[334] =  new ASCIIUNIMAP("¨sÁ","ಭಾ");
asciiUniMap[335] =  new ASCIIUNIMAP("¨ÉÊ","ಬೈ");
asciiUniMap[336] =  new ASCIIUNIMAP("¨ÉÆ","ಬೊ");
asciiUniMap[337] =  new ASCIIUNIMAP("¨ÉÃ","ಬೇ");
asciiUniMap[338] =  new ASCIIUNIMAP("¦üÃ","ಫೀ");
asciiUniMap[339] =  new ASCIIUNIMAP("WÉÊ","ಘೈ");
asciiUniMap[340] =  new ASCIIUNIMAP("¥ÀÄ","ಪು");
asciiUniMap[341] =  new ASCIIUNIMAP("¥ÀÄ","ಪು");
asciiUniMap[342] =  new ASCIIUNIMAP("¥ÀÆ","ಪು");
asciiUniMap[343] =  new ASCIIUNIMAP("¥ÉÆ","ಪೊ");
asciiUniMap[344] =  new ASCIIUNIMAP("PÁë","ಕ್ಷಾ");
asciiUniMap[345] =  new ASCIIUNIMAP("PÁë","ಕ್ಷಾ");
asciiUniMap[346] =  new ASCIIUNIMAP("QëÃ","ಕ್ಷೀ");
asciiUniMap[347] =  new ASCIIUNIMAP("PÉë","ಕ್ಷೆ");
asciiUniMap[348] =  new ASCIIUNIMAP("PËë","ಕ್ಷೌ");
asciiUniMap[349] =  new ASCIIUNIMAP("eÁÕ","ಜ್ಞಾ");
asciiUniMap[350] =  new ASCIIUNIMAP("fÕÃ","ಜ್ಞೀ");
asciiUniMap[351] =  new ASCIIUNIMAP("dÄÕ","ಜ್ಞು");
asciiUniMap[352] =  new ASCIIUNIMAP("dÆÕ","ಜ್ಞೂ");
asciiUniMap[353] =  new ASCIIUNIMAP("dÕø","ಜ್ಞೃ");
asciiUniMap[354] =  new ASCIIUNIMAP("eÉÕ","ಜ್ಞೆ");
asciiUniMap[355] =  new ASCIIUNIMAP("eËÕ","ಜ್ಞೌ");
asciiUniMap[356] =  new ASCIIUNIMAP("Pï ","ಕ್ ");
asciiUniMap[357] =  new ASCIIUNIMAP("SÁó","ಖಾ಼");
asciiUniMap[358] =  new ASCIIUNIMAP("RÄó","ಖು಼");
asciiUniMap[359] =  new ASCIIUNIMAP("RÆó","ಖೂ಼");
asciiUniMap[360] =  new ASCIIUNIMAP("RóÈ","ಖ಼");
asciiUniMap[361] =  new ASCIIUNIMAP("SÉó","ಖೆ಼");
asciiUniMap[362] =  new ASCIIUNIMAP("SËó","ಖೌ಼");
asciiUniMap[363] =  new ASCIIUNIMAP("eÁó","ಜಾ಼");
asciiUniMap[364] =  new ASCIIUNIMAP("fÃó","ಜೀ಼");
asciiUniMap[365] =  new ASCIIUNIMAP("dÄó","ಜು಼");
asciiUniMap[366] =  new ASCIIUNIMAP("dÆó","ಜೂ಼");
asciiUniMap[367] =  new ASCIIUNIMAP("dûÈ","ಜ಼");
asciiUniMap[368] =  new ASCIIUNIMAP("eóÉ","ಜೆ಼");
asciiUniMap[369] =  new ASCIIUNIMAP("eóË","ಜೌ಼");
asciiUniMap[370] =  new ASCIIUNIMAP("¦üû","ಫಿ಼");
asciiUniMap[371] =  new ASCIIUNIMAP("PÀñ","ಕೄ");
asciiUniMap[372] =  new ASCIIUNIMAP("UÀñ","ಗೄ");
asciiUniMap[373] =  new ASCIIUNIMAP("WÀñ","ಘೄ");
asciiUniMap[374] =  new ASCIIUNIMAP("ZÀñ","ಚೄ");
asciiUniMap[375] =  new ASCIIUNIMAP("bÀñ","ಛೄ");
asciiUniMap[376] =  new ASCIIUNIMAP("oÀñ","ಠೄ");
asciiUniMap[377] =  new ASCIIUNIMAP("qÀñ","ಡೄ");
asciiUniMap[378] =  new ASCIIUNIMAP("vÀñ","ತೄ");
asciiUniMap[379] =  new ASCIIUNIMAP("xÀñ","ಥೄ");
asciiUniMap[380] =  new ASCIIUNIMAP("£Àñ","ನೄ");
asciiUniMap[381] =  new ASCIIUNIMAP("¥Àñ","ಪೄ");
asciiUniMap[382] =  new ASCIIUNIMAP("gÀñ","ರೄ");
asciiUniMap[383] =  new ASCIIUNIMAP("ªÀñ","ವೄ");
asciiUniMap[384] =  new ASCIIUNIMAP("±Àñ","ಶೄ");
asciiUniMap[385] =  new ASCIIUNIMAP("µÀñ","ಷೄ");
asciiUniMap[386] =  new ASCIIUNIMAP("¸Àñ","ಸೄ");
asciiUniMap[387] =  new ASCIIUNIMAP("ºÀñ","ಹೄ");
asciiUniMap[388] =  new ASCIIUNIMAP("¼Àñ","ಳೄ");
asciiUniMap[389] =  new ASCIIUNIMAP("uÉÃ","ಣೇ");
asciiUniMap[390] =  new ASCIIUNIMAP("uÉÊ","ಣೈ");
asciiUniMap[391] =  new ASCIIUNIMAP("uÉÆ","ಣೊ");
asciiUniMap[392] =  new ASCIIUNIMAP("zÀÄ","ದು");
asciiUniMap[393] =  new ASCIIUNIMAP("zÀÆ","ದೂ");
asciiUniMap[394] =  new ASCIIUNIMAP("zÀÈ","ದೃ");
asciiUniMap[395] =  new ASCIIUNIMAP("zÉÃ","ದೇ");
asciiUniMap[396] =  new ASCIIUNIMAP("zÉÊ","ದೈ");
asciiUniMap[397] =  new ASCIIUNIMAP("zÉÆ","ದೊ");
asciiUniMap[398] =  new ASCIIUNIMAP("zÀs ","ಧ");
asciiUniMap[399] =  new ASCIIUNIMAP("Zï","ಚ್");
asciiUniMap[400] =  new ASCIIUNIMAP("ZË","ಚೌ");
asciiUniMap[401] =  new ASCIIUNIMAP("ZÉ","ಚೆ");
asciiUniMap[402] =  new ASCIIUNIMAP("ZÀ","ಚ");
asciiUniMap[403] =  new ASCIIUNIMAP("ZÁ","ಚಾ");
asciiUniMap[404] =  new ASCIIUNIMAP("Yï","ಙ್");
asciiUniMap[405] =  new ASCIIUNIMAP("YË","ಙೌ");
asciiUniMap[406] =  new ASCIIUNIMAP("YÈ","ಙೃ");
asciiUniMap[407] =  new ASCIIUNIMAP("YÉ","ಙೆ");
asciiUniMap[408] =  new ASCIIUNIMAP("YÐ","ಙ್ಙ");
asciiUniMap[409] =  new ASCIIUNIMAP("YB","ಙಃ");
asciiUniMap[410] =  new ASCIIUNIMAP("YÆ","ಙೂ");
asciiUniMap[411] =  new ASCIIUNIMAP("yÃ","ಥೀ");
asciiUniMap[412] =  new ASCIIUNIMAP("YÄ","ಙು");
asciiUniMap[413] =  new ASCIIUNIMAP("YÂ","ಙಿ");
asciiUniMap[414] =  new ASCIIUNIMAP("YÁ","ಙಾ");
asciiUniMap[415] =  new ASCIIUNIMAP("xï","ಥ್");
asciiUniMap[416] =  new ASCIIUNIMAP("xË","ಥೌ");
asciiUniMap[417] =  new ASCIIUNIMAP("xÉ","ಥೆ");
asciiUniMap[418] =  new ASCIIUNIMAP("XÃ","ಘೀ");
asciiUniMap[419] =  new ASCIIUNIMAP("xÀ","ಥ");
asciiUniMap[420] =  new ASCIIUNIMAP("xÁ","ಥಾ");
asciiUniMap[421] =  new ASCIIUNIMAP("Wï","ಘ್");
asciiUniMap[422] =  new ASCIIUNIMAP("WË","ಘೌ");
asciiUniMap[423] =  new ASCIIUNIMAP("WÉ","ಘೆ");
asciiUniMap[424] =  new ASCIIUNIMAP("wÃ","ತೀ");
asciiUniMap[425] =  new ASCIIUNIMAP("WÀ","ಘ");
asciiUniMap[426] =  new ASCIIUNIMAP("WÁ","ಘಾ");
asciiUniMap[427] =  new ASCIIUNIMAP("vï","ತ್");
asciiUniMap[428] =  new ASCIIUNIMAP("vË","ತೌ");
asciiUniMap[429] =  new ASCIIUNIMAP("vÉ","ತೆ");
asciiUniMap[430] =  new ASCIIUNIMAP("VÃ","ಗೀ");
asciiUniMap[431] =  new ASCIIUNIMAP("vÀ","ತ");
asciiUniMap[432] =  new ASCIIUNIMAP("vÁ","ತಾ");
asciiUniMap[433] =  new ASCIIUNIMAP("Uï","ಗ್");
asciiUniMap[434] =  new ASCIIUNIMAP("UË","ಗೌ");
asciiUniMap[435] =  new ASCIIUNIMAP("UÉ","ಗೆ");
asciiUniMap[436] =  new ASCIIUNIMAP("UÀ","ಗ");
asciiUniMap[437] =  new ASCIIUNIMAP("UÁ","ಗಾ");
asciiUniMap[438] =  new ASCIIUNIMAP("tÚ","ಣ್ಣ");
asciiUniMap[439] =  new ASCIIUNIMAP("tÈ","ಣೃ");
asciiUniMap[440] =  new ASCIIUNIMAP("tB","ಣಃ");
asciiUniMap[441] =  new ASCIIUNIMAP("tÆ","ಣೂ");
asciiUniMap[442] =  new ASCIIUNIMAP("TÃ","ಖೀ");
asciiUniMap[443] =  new ASCIIUNIMAP("tÄ","ಣು");
asciiUniMap[444] =  new ASCIIUNIMAP("tÂ","ಣಿ");
asciiUniMap[445] =  new ASCIIUNIMAP("Sï","ಖ್");
asciiUniMap[446] =  new ASCIIUNIMAP("SË","ಖೌ");
asciiUniMap[447] =  new ASCIIUNIMAP("SÉ","ಖೆ");
asciiUniMap[448] =  new ASCIIUNIMAP("SÁ","ಖಾ");
asciiUniMap[449] =  new ASCIIUNIMAP("rü","ಢಿ");
asciiUniMap[450] =  new ASCIIUNIMAP("RÍ","ಖ್ಖ");
asciiUniMap[451] =  new ASCIIUNIMAP("RÈ","ಖೃ");
asciiUniMap[452] =  new ASCIIUNIMAP("RB","ಖಃ");
asciiUniMap[453] =  new ASCIIUNIMAP("RÆ","ಖೂ");
asciiUniMap[454] =  new ASCIIUNIMAP("rÃ","ಡೀ");
asciiUniMap[455] =  new ASCIIUNIMAP("RÄ","ಖು");
asciiUniMap[456] =  new ASCIIUNIMAP("qï","ಡ್");
asciiUniMap[457] =  new ASCIIUNIMAP("qË","ಡೌ");
asciiUniMap[458] =  new ASCIIUNIMAP("qÉ","ಡೆ");
asciiUniMap[459] =  new ASCIIUNIMAP("QÃ","ಕೀ");
asciiUniMap[460] =  new ASCIIUNIMAP("qÀ","ಡ");
asciiUniMap[461] =  new ASCIIUNIMAP("qÁ","ಡಾ");
asciiUniMap[462] =  new ASCIIUNIMAP("Pï","ಕ್");
asciiUniMap[463] =  new ASCIIUNIMAP("PË","ಕೌ");
asciiUniMap[464] =  new ASCIIUNIMAP("PÉ","ಕೆ");
asciiUniMap[465] =  new ASCIIUNIMAP("pÃ","ಠೀ");
asciiUniMap[466] =  new ASCIIUNIMAP("PÀ","ಕ");
asciiUniMap[467] =  new ASCIIUNIMAP("PÁ","ಕಾ");
asciiUniMap[468] =  new ASCIIUNIMAP("ºï","ಹ್");
asciiUniMap[469] =  new ASCIIUNIMAP("oï","ಠ್");
asciiUniMap[470] =  new ASCIIUNIMAP("ºË","ಹೌ");
asciiUniMap[471] =  new ASCIIUNIMAP("ºÉ","ಹೆ");
asciiUniMap[472] =  new ASCIIUNIMAP("oË","ಠೌ");
asciiUniMap[473] =  new ASCIIUNIMAP("oÉ","ಠೆ");
asciiUniMap[474] =  new ASCIIUNIMAP("ºÀ","ಹ");
asciiUniMap[475] =  new ASCIIUNIMAP("ºÁ","ಹಾ");
asciiUniMap[476] =  new ASCIIUNIMAP("oÀ","ಠ");
asciiUniMap[477] =  new ASCIIUNIMAP("oÁ","ಠಾ");
asciiUniMap[478] =  new ASCIIUNIMAP("nÃ","ಟೀ");
asciiUniMap[479] =  new ASCIIUNIMAP("mï","ಟ್");
asciiUniMap[480] =  new ASCIIUNIMAP("mË","ಟೌ");
asciiUniMap[481] =  new ASCIIUNIMAP("mÉ","ಟೆ");
asciiUniMap[482] =  new ASCIIUNIMAP("mÁ","ಟಾ");
asciiUniMap[483] =  new ASCIIUNIMAP("lÖ","ಟ್ಟ");
asciiUniMap[484] =  new ASCIIUNIMAP("lÈ","ಟೃ");
asciiUniMap[485] =  new ASCIIUNIMAP("lB","ಟಃ");
asciiUniMap[486] =  new ASCIIUNIMAP("lÆ","ಟೂ");
asciiUniMap[487] =  new ASCIIUNIMAP("lÄ","ಟು");
asciiUniMap[488] =  new ASCIIUNIMAP("kÕ","ಞ್ಞ");
asciiUniMap[489] =  new ASCIIUNIMAP("kï","ಞ್");
asciiUniMap[490] =  new ASCIIUNIMAP("kË","ಞೌ");
asciiUniMap[491] =  new ASCIIUNIMAP("kÈ","ಞೃ");
asciiUniMap[492] =  new ASCIIUNIMAP("kÉ","ಙೆ");
asciiUniMap[493] =  new ASCIIUNIMAP("kB","ಞಃ");
asciiUniMap[494] =  new ASCIIUNIMAP("kÆ","ಞೂ");
asciiUniMap[495] =  new ASCIIUNIMAP("kÄ","ಞು");
asciiUniMap[496] =  new ASCIIUNIMAP("kÂ","ಞಿ");
asciiUniMap[497] =  new ASCIIUNIMAP("kÁ","ಞಾ");
asciiUniMap[498] =  new ASCIIUNIMAP("jÃ","ರೀ");
asciiUniMap[499] =  new ASCIIUNIMAP("IÄ","ಋ");
asciiUniMap[500] =  new ASCIIUNIMAP("gï","ರ್");
asciiUniMap[501] =  new ASCIIUNIMAP("gË","ರೌ");
asciiUniMap[502] =  new ASCIIUNIMAP("gÉ","ರೆ");
asciiUniMap[503] =  new ASCIIUNIMAP("gÀ","ರ");
asciiUniMap[504] =  new ASCIIUNIMAP("gÁ","ರಾ");
asciiUniMap[505] =  new ASCIIUNIMAP("fÕ","ಜ್ಞಿ");
asciiUniMap[506] =  new ASCIIUNIMAP("fÃ","ಜೀ");
asciiUniMap[507] =  new ASCIIUNIMAP("eï","ಜ್");
asciiUniMap[508] =  new ASCIIUNIMAP("eË","ಜೌ");
asciiUniMap[509] =  new ASCIIUNIMAP("eÉ","ಜೆ");
asciiUniMap[510] =  new ASCIIUNIMAP("eÁ","ಜಾ");
asciiUniMap[511] =  new ASCIIUNIMAP("dÕ","ಜ್ಞ");
asciiUniMap[512] =  new ASCIIUNIMAP("dÓ","ಜ್ಜ");
asciiUniMap[513] =  new ASCIIUNIMAP("dÈ","ಜೃ");
asciiUniMap[514] =  new ASCIIUNIMAP("dB","ಜಃ");
asciiUniMap[515] =  new ASCIIUNIMAP("dÆ","ಜೂ");
asciiUniMap[516] =  new ASCIIUNIMAP("dÄ","ಜು");
asciiUniMap[517] =  new ASCIIUNIMAP("CB","ಅಃ");
asciiUniMap[518] =  new ASCIIUNIMAP("cÃ","ಛೀ");
asciiUniMap[519] =  new ASCIIUNIMAP("bï","ಛ್");
asciiUniMap[520] =  new ASCIIUNIMAP("bË","ಛೌ");
asciiUniMap[521] =  new ASCIIUNIMAP("bÉ","ಛೆ");
asciiUniMap[522] =  new ASCIIUNIMAP("bÀ","ಛ");
asciiUniMap[523] =  new ASCIIUNIMAP("bÁ","ಛಾ");
asciiUniMap[524] =  new ASCIIUNIMAP("ªï","ವ್");
asciiUniMap[525] =  new ASCIIUNIMAP("æç","್ರ");
asciiUniMap[526] =  new ASCIIUNIMAP("ªË","ವೌ");
asciiUniMap[527] =  new ASCIIUNIMAP("ªÉ","ವೆ");
asciiUniMap[528] =  new ASCIIUNIMAP("ªÀ","ವ");
asciiUniMap[529] =  new ASCIIUNIMAP("ªÁ","ವಾ");
asciiUniMap[530] =  new ASCIIUNIMAP("aÃ","ಚೀ");
asciiUniMap[531] =  new ASCIIUNIMAP("²Ã","ಶೀ");
asciiUniMap[532] =  new ASCIIUNIMAP("¹Ã","ಸೀ");
asciiUniMap[533] =  new ASCIIUNIMAP("½Ã","ಳೀ");
asciiUniMap[534] =  new ASCIIUNIMAP("¼ï","ಳ್");
asciiUniMap[535] =  new ASCIIUNIMAP("¼Ë","ಳೌ");
asciiUniMap[536] =  new ASCIIUNIMAP("¼É","ಳೆ");
asciiUniMap[537] =  new ASCIIUNIMAP("¼À","ಳ");
asciiUniMap[538] =  new ASCIIUNIMAP("¼Á","ಳಾ");
asciiUniMap[539] =  new ASCIIUNIMAP("¶Ã","ಷೀ");
asciiUniMap[540] =  new ASCIIUNIMAP("µË","ಷೌ");
asciiUniMap[541] =  new ASCIIUNIMAP("µÉ","ಷೆ");
asciiUniMap[542] =  new ASCIIUNIMAP("µÀ","ಷ");
asciiUniMap[543] =  new ASCIIUNIMAP("µÁ","ಷಾ");
asciiUniMap[544] =  new ASCIIUNIMAP("°Ã","ಲೀ");
asciiUniMap[545] =  new ASCIIUNIMAP("®È","ಲೃ");
asciiUniMap[546] =  new ASCIIUNIMAP("®B","ಲಃ");
asciiUniMap[547] =  new ASCIIUNIMAP("®Æ","ಲೂ");
asciiUniMap[548] =  new ASCIIUNIMAP("®Ä","ಲು");
asciiUniMap[549] =  new ASCIIUNIMAP("¬Ä","ಯಿ");
asciiUniMap[550] =  new ASCIIUNIMAP("©ü","ಭಿ");
asciiUniMap[551] =  new ASCIIUNIMAP("©Ã","ಬೀ");
asciiUniMap[552] =  new ASCIIUNIMAP("§È","ಬೃ");
asciiUniMap[553] =  new ASCIIUNIMAP("§B","ಬಃ");
asciiUniMap[554] =  new ASCIIUNIMAP("§Æ","ಬೂ");
asciiUniMap[555] =  new ASCIIUNIMAP("§Ä","ಬು");
asciiUniMap[556] =  new ASCIIUNIMAP("§â","ಬ್ಬ");
asciiUniMap[557] =  new ASCIIUNIMAP("§A","ಬಂ");
asciiUniMap[558] =  new ASCIIUNIMAP("¥ï","ಪ್");
asciiUniMap[559] =  new ASCIIUNIMAP("¥Ë","ಪೌ");
asciiUniMap[560] =  new ASCIIUNIMAP("¥É","ಪೆ");
asciiUniMap[561] =  new ASCIIUNIMAP("¥À","ಪ");
asciiUniMap[562] =  new ASCIIUNIMAP("¥Á","ಪಾ");
asciiUniMap[563] =  new ASCIIUNIMAP("¤Ã","ನೀ");
asciiUniMap[564] =  new ASCIIUNIMAP("£ï","ನ್");
asciiUniMap[565] =  new ASCIIUNIMAP("£Ë","ನೌ");
asciiUniMap[566] =  new ASCIIUNIMAP("£É","ನೆ");
asciiUniMap[567] =  new ASCIIUNIMAP("£À","ನ");
asciiUniMap[568] =  new ASCIIUNIMAP("£Á","ನಾ");
asciiUniMap[569] =  new ASCIIUNIMAP("¢ü","ಧಿ");
asciiUniMap[570] =  new ASCIIUNIMAP("¢Ã","ದೀ");
asciiUniMap[571] =  new ASCIIUNIMAP("»Ã","ಹೀ");
asciiUniMap[572] =  new ASCIIUNIMAP("«Ã","ವೀ");
asciiUniMap[573] =  new ASCIIUNIMAP("«Ä","ಮಿ");
asciiUniMap[574] =  new ASCIIUNIMAP("±ï","ಶ್");
asciiUniMap[575] =  new ASCIIUNIMAP("±Ë","ಶೌ");
asciiUniMap[576] =  new ASCIIUNIMAP("±É","ಶೆ");
asciiUniMap[577] =  new ASCIIUNIMAP("±À","ಶ");
asciiUniMap[578] =  new ASCIIUNIMAP("±Á","ಶಾ");
asciiUniMap[579] =  new ASCIIUNIMAP("¸ï","ಸ್");
asciiUniMap[580] =  new ASCIIUNIMAP("¸Ë","ಸೌ");
asciiUniMap[581] =  new ASCIIUNIMAP("¸É","ಸೆ");
asciiUniMap[582] =  new ASCIIUNIMAP("¸À","ಸ");
asciiUniMap[583] =  new ASCIIUNIMAP("¸Á","ಸಾ");
asciiUniMap[584] =  new ASCIIUNIMAP("¯ï","ಲ್");
asciiUniMap[585] =  new ASCIIUNIMAP("¯Ë","ಲೌ");
asciiUniMap[586] =  new ASCIIUNIMAP("¯É","ಲೆ");
asciiUniMap[587] =  new ASCIIUNIMAP("¯Á","ಲಾ");
asciiUniMap[588] =  new ASCIIUNIMAP("¨ï","ಬ್");
asciiUniMap[589] =  new ASCIIUNIMAP("¨Ë","ಬೌ");
asciiUniMap[590] =  new ASCIIUNIMAP("¨É","ಬೆ");
asciiUniMap[591] =  new ASCIIUNIMAP("¨Á","ಬಾ");
asciiUniMap[592] =  new ASCIIUNIMAP("¦ü","ಫಿ");
asciiUniMap[593] =  new ASCIIUNIMAP("¦Ã","ಪೀ");
asciiUniMap[594] =  new ASCIIUNIMAP("µï","ಷ್");
asciiUniMap[595] =  new ASCIIUNIMAP("Ró","ಖ಼");
asciiUniMap[596] =  new ASCIIUNIMAP("Tó","ಖಿ಼");
asciiUniMap[597] =  new ASCIIUNIMAP("dû","ಜ಼");
asciiUniMap[598] =  new ASCIIUNIMAP("fó","ಜಿ಼");
asciiUniMap[599] =  new ASCIIUNIMAP("Rñ","ಖೄ");
asciiUniMap[600] =  new ASCIIUNIMAP("Yñ","ಙೄ");
asciiUniMap[601] =  new ASCIIUNIMAP("dñ","ಜೄ");
asciiUniMap[602] =  new ASCIIUNIMAP("kñ","ಞೄ");
asciiUniMap[603] =  new ASCIIUNIMAP("lñ","ಟೄ");
asciiUniMap[604] =  new ASCIIUNIMAP("tñ","ಣೄ");
asciiUniMap[605] =  new ASCIIUNIMAP("§ñ","ಬೄ");
asciiUniMap[606] =  new ASCIIUNIMAP("®ñ","ಲೄ");
asciiUniMap[607] =  new ASCIIUNIMAP("YÁ","ಙಾ");
asciiUniMap[608] =  new ASCIIUNIMAP("kÉ","ಞೆ");
asciiUniMap[609] =  new ASCIIUNIMAP("uÁ","ಣಾ");
asciiUniMap[610] =  new ASCIIUNIMAP("uÉ","ಣೆ");
asciiUniMap[611] =  new ASCIIUNIMAP("uË","ಣೌ");
asciiUniMap[612] =  new ASCIIUNIMAP("zÀ","ದ");
asciiUniMap[613] =  new ASCIIUNIMAP("zÉ","ದೆ");
asciiUniMap[614] =  new ASCIIUNIMAP("zË","ದೌ");
asciiUniMap[615] =  new ASCIIUNIMAP("¥À","ಫ");
asciiUniMap[616] =  new ASCIIUNIMAP("ªÉ","ವೆ");
asciiUniMap[617] =  new ASCIIUNIMAP("uï","ಣ್");
asciiUniMap[618] =  new ASCIIUNIMAP("zï","ದ್");
asciiUniMap[619] =  new ASCIIUNIMAP("kÉ","ಞೆ");
asciiUniMap[620] =  new ASCIIUNIMAP("zÁ","ದಾ");
asciiUniMap[621] =  new ASCIIUNIMAP("Þ","್ಧ");
asciiUniMap[622] =  new ASCIIUNIMAP("Ú","್ಣ");
asciiUniMap[623] =  new ASCIIUNIMAP("Ù","್ಢ");
asciiUniMap[624] =  new ASCIIUNIMAP("Ý","್ದ");
asciiUniMap[625] =  new ASCIIUNIMAP("Y","ಙ");
asciiUniMap[626] =  new ASCIIUNIMAP("X","ಘಿ");
asciiUniMap[627] =  new ASCIIUNIMAP("w","ತಿ");
asciiUniMap[628] =  new ASCIIUNIMAP("V","ಗಿ");
asciiUniMap[629] =  new ASCIIUNIMAP("Ü","್ಥ");
asciiUniMap[630] =  new ASCIIUNIMAP("Û","್ತ");
asciiUniMap[631] =  new ASCIIUNIMAP("Þ","್ಧ");
asciiUniMap[632] =  new ASCIIUNIMAP("T","ಖಿ");
asciiUniMap[633] =  new ASCIIUNIMAP("ß","್ನ");
asciiUniMap[634] =  new ASCIIUNIMAP("R","ಖ");
asciiUniMap[635] =  new ASCIIUNIMAP("Q","ಕಿ");
asciiUniMap[636] =  new ASCIIUNIMAP("p","ಠಿ");
asciiUniMap[637] =  new ASCIIUNIMAP("Õ","್ಞ");
asciiUniMap[638] =  new ASCIIUNIMAP("Ö","್ಟ");
asciiUniMap[639] =  new ASCIIUNIMAP("Ô","್ಝ");
asciiUniMap[640] =  new ASCIIUNIMAP("Ò","್ಛ");
asciiUniMap[641] =  new ASCIIUNIMAP("Ó","್ಜ");
asciiUniMap[642] =  new ASCIIUNIMAP("O","ಔ");
asciiUniMap[643] =  new ASCIIUNIMAP("Ñ","್ಚ");
asciiUniMap[644] =  new ASCIIUNIMAP("N","ಓ");
asciiUniMap[645] =  new ASCIIUNIMAP("M","ಒ");
asciiUniMap[646] =  new ASCIIUNIMAP("L","ಐ");
asciiUniMap[647] =  new ASCIIUNIMAP("K","ಏ");
asciiUniMap[648] =  new ASCIIUNIMAP("J","ಎ");
asciiUniMap[649] =  new ASCIIUNIMAP("Ï","್ಘ");
asciiUniMap[650] =  new ASCIIUNIMAP("Î","್ಗ");
asciiUniMap[651] =  new ASCIIUNIMAP("Ì","್ಕ");
asciiUniMap[652] =  new ASCIIUNIMAP("í","್ಹ");
asciiUniMap[653] =  new ASCIIUNIMAP("H","ಊ");
asciiUniMap[654] =  new ASCIIUNIMAP("G","ಉ");
asciiUniMap[655] =  new ASCIIUNIMAP("F","ಈ");
asciiUniMap[656] =  new ASCIIUNIMAP("ë","್ಷ");
asciiUniMap[657] =  new ASCIIUNIMAP("ê","್ಶ");
asciiUniMap[658] =  new ASCIIUNIMAP("è","್ಲ");
asciiUniMap[659] =  new ASCIIUNIMAP("é","್ವ");
asciiUniMap[660] =  new ASCIIUNIMAP("E","ಇ");
asciiUniMap[661] =  new ASCIIUNIMAP("Ð","್ಙ");
asciiUniMap[662] =  new ASCIIUNIMAP("D","ಆ");
asciiUniMap[663] =  new ASCIIUNIMAP("C","ಅ");
asciiUniMap[664] =  new ASCIIUNIMAP("æ","್ರ");
asciiUniMap[665] =  new ASCIIUNIMAP("å","್ಯ");
asciiUniMap[666] =  new ASCIIUNIMAP("ã","್ಭ");
asciiUniMap[667] =  new ASCIIUNIMAP("ä","್ಮ");
asciiUniMap[668] =  new ASCIIUNIMAP("â","್ಬ");
asciiUniMap[669] =  new ASCIIUNIMAP("à","್ಪ");
asciiUniMap[670] =  new ASCIIUNIMAP("á","್ಫ");
asciiUniMap[671] =  new ASCIIUNIMAP("a","ಚಿ");
asciiUniMap[672] =  new ASCIIUNIMAP("²","ಶಿ");
asciiUniMap[673] =  new ASCIIUNIMAP("½","ಳಿ");
asciiUniMap[674] =  new ASCIIUNIMAP("¶","ಷಿ");
asciiUniMap[675] =  new ASCIIUNIMAP("°","ಲಿ");
asciiUniMap[676] =  new ASCIIUNIMAP("®","ಲ");
asciiUniMap[677] =  new ASCIIUNIMAP("©","ಬಿ");
asciiUniMap[678] =  new ASCIIUNIMAP("§","ಬ");
asciiUniMap[679] =  new ASCIIUNIMAP("¤","ನಿ");
asciiUniMap[680] =  new ASCIIUNIMAP("¢","ದಿ");
asciiUniMap[681] =  new ASCIIUNIMAP("×","್ಠ");
asciiUniMap[682] =  new ASCIIUNIMAP("»","ಹಿ");
asciiUniMap[683] =  new ASCIIUNIMAP("«","ವಿ");
asciiUniMap[684] =  new ASCIIUNIMAP("¦","ಪಿ");
asciiUniMap[685] =  new ASCIIUNIMAP("ç","್ರ");
asciiUniMap[686] =  new ASCIIUNIMAP("ø","ೃ");
asciiUniMap[687] =  new ASCIIUNIMAP("B","ಃ");
asciiUniMap[688] =  new ASCIIUNIMAP("A","ಂ");
asciiUniMap[689] =  new ASCIIUNIMAP("Ã","ೕ");
asciiUniMap[690] =  new ASCIIUNIMAP("È","ೃ");
asciiUniMap[691] =  new ASCIIUNIMAP("Ê","ೖ");
asciiUniMap[692] =  new ASCIIUNIMAP("d","ಜ");
asciiUniMap[693] =  new ASCIIUNIMAP("f","ಜಿ");
asciiUniMap[694] =  new ASCIIUNIMAP("k","ಞ");
asciiUniMap[695] =  new ASCIIUNIMAP("l","ಟ");
asciiUniMap[696] =  new ASCIIUNIMAP("t","ಣ");
asciiUniMap[697] =  new ASCIIUNIMAP("¦","ಫಿ");
asciiUniMap[698] =  new ASCIIUNIMAP("j","ರಿ");
asciiUniMap[699] =  new ASCIIUNIMAP("¹","ಸಿ");
asciiUniMap[700] =  new ASCIIUNIMAP("ð","ರ್");
asciiUniMap[701] =  new ASCIIUNIMAP("c","ಛಿ");
asciiUniMap[702] =  new ASCIIUNIMAP("n","ಟಿ");
asciiUniMap[703] =  new ASCIIUNIMAP("r","ಡಿ");
asciiUniMap[704] =  new ASCIIUNIMAP("y","ಥಿ");
asciiUniMap[705] =  new ASCIIUNIMAP("ì","್ಸ");
asciiUniMap[706] =  new ASCIIUNIMAP("É","ೆ");
asciiUniMap[707] =  new ASCIIUNIMAP("î","್ಳ");
asciiUniMap[714] =  new ASCIIUNIMAP("Í","್ಖ");
asciiUniMap[715] =  new ASCIIUNIMAP("Ø","್ಡ");
asciiUniMap[716] =  new ASCIIUNIMAP("Ä","Ä");

                                                                           asciiUniMap[711]=new ASCIIUNIMAP("\b","\b");
                                                                           asciiUniMap[712]=new ASCIIUNIMAP("\t","\t");
                                                                           asciiUniMap[713]=new ASCIIUNIMAP("\f","\f");
                                                                           asciiUniMap[708]=new ASCIIUNIMAP("\r","\r");
                                                                           asciiUniMap[709]=new ASCIIUNIMAP("\0","\0");
                                                                           asciiUniMap[710]=new ASCIIUNIMAP("\n","\n");
		intitalizeOttaksharaList();
		initializeGunitaaksharaList();
		return true;
	}
	public static void initializeGunitaaksharaList(){
		gunitakshara.add("ಾ");
		gunitakshara.add("ಿ");
		gunitakshara.add("ೀ");
		gunitakshara.add("ು");
		gunitakshara.add("ೂ");
		gunitakshara.add("ೃ");
		gunitakshara.add("ೆ");
		gunitakshara.add("ೇ");
		gunitakshara.add("ೈ");
		gunitakshara.add("ೊ");
		gunitakshara.add("ೋ");
		gunitakshara.add("ೌ");

	}
	public static void intitalizeOttaksharaList(){
				ottaksharaList.add("್ಕ");
				ottaksharaList.add("್ಗ");
				ottaksharaList.add("್ಘ");
				ottaksharaList.add("್ಙ");
				ottaksharaList.add("್ಙ");
				ottaksharaList.add("್ಚ");
				ottaksharaList.add("್ಛ");
				ottaksharaList.add("್ಜ");
				ottaksharaList.add("್ಜ");
				ottaksharaList.add("್ಝ");
				ottaksharaList.add("್ಞ");
				ottaksharaList.add("್ಞ");
				ottaksharaList.add("್ಟ");
				ottaksharaList.add("್ಟ");
				ottaksharaList.add("್ಠ");
				ottaksharaList.add("್ಡ");
				ottaksharaList.add("್ಢ");
				ottaksharaList.add("್ಢ");
				ottaksharaList.add("್ಢ");
				ottaksharaList.add("್ಣ");
				ottaksharaList.add("್ಣ");
				ottaksharaList.add("್ಣ್");
				ottaksharaList.add("್ತ");
				ottaksharaList.add("್ಥ");
				ottaksharaList.add("್ದ");
				ottaksharaList.add("್ಧ");
				ottaksharaList.add("್ಧ");
				ottaksharaList.add("್ಧ");
				ottaksharaList.add("್ನ");
				ottaksharaList.add("್ಪ");
				ottaksharaList.add("್ಪ");
				ottaksharaList.add("್ಫ");
				ottaksharaList.add("್ಫ");
				ottaksharaList.add("್ಬ");
				ottaksharaList.add("್ಬ");
				ottaksharaList.add("್ಭ");
				ottaksharaList.add("್ಭ");
				ottaksharaList.add("್ಭ");
				ottaksharaList.add("್ಮ");
				ottaksharaList.add("್ಯ");
				ottaksharaList.add("್ರ");
				ottaksharaList.add("್ರ");
				ottaksharaList.add("್ರ");
				ottaksharaList.add("್ರ");
				ottaksharaList.add("್ಲ");
				ottaksharaList.add("್ಲ");
				ottaksharaList.add("್ವ");
				ottaksharaList.add("್ಶ");
				ottaksharaList.add("್ಶ");
				ottaksharaList.add("್ಷ");
				ottaksharaList.add("್ಷ");
				ottaksharaList.add("್ಹ");
				ottaksharaList.add("್ಹ");
                                ottaksharaList.add("್ಸ");
                                ottaksharaList.add("್ಳ");

	}
	public void initializeMap() {
		// TODO Auto-generated method stub
		
	}
	public String Convert(String inText) {
		// TODO Auto-generated method stub
		return null;
	}
	                  
}
